bootstrap_servers:
  - http://localhost:9092
feeds:
  - name: feed1
    url: https://feed1_url
    format: json
    maxRetries: x
    baseDelay: x
    heartBeatInterval: x
    maxJitterMillis: k
    pongTimeout: x
    kafkaTopic: x
    kafkaBatchSize: x
    ringBufferSize: z

  - name: feed2
    url: https://feed2_url
    format: csv
    maxRetries: z
    baseDelay: z
    heartBeatInterval: z
    maxJitterMillis: k
    pongTimeout: z
    kafkaTopic: z
    kafkaBatchSize: z
    ringBufferSize: z

  - name: feed3
    url: https://feed3_url
    format: fix
    maxRetries: k
    baseDelay: k
    heartBeatInterval: k
    maxJitterMillis: k
    pongTimeout: k
    kafkaTopic: k
    kafkaBatchSize: k
    ringBufferSize: z