kafka:
  brokers:
    - localhost:9092
  topics:
    - "binance.raw.ticks"
    - "binance.raw.level2"
    - "coinbase.raw.ticks"
    - "coinbase.raw.level2"
    - "kraken.raw.ticks"
    - "kraken.raw.book"
  consumer_group: normalizer-group-1
  max_buffer_records: 5000
  commit_offset_interval_millis: 5000
  backpressure:
    queue_usage_high_threshold: 0.8
    queue_usage_low_threshold: 0.4
    threshold_active_millis: 5000
    cooldown_time_millis: 5000

worker_count: 16
redis:
  ttl_minutes: 15
  cb_req_count: 10
  cb_failure_ratio: 0.25
  cb_timeout_millis: 5000