kafka:
  brokers:
    - localhost:9092
  topics:
    - "binance_raw_aggtrades"
    - "binance_raw_depth"
    - "coinbase_raw_ticker"
    - "coinbase_raw_depth"
    - "kraken_raw_ticker"
    - "kraken_raw_depth"
  consumer_group: normalizer-group-1
  max_buffer_records: 5000
  commit_offset_interval_millis: 5000

worker_count: 16
redis_ttl_minutes: 15   